### ISSUE TITLE
Equivalence Checking Runtime Exception

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#18]
I tried to write equivalence check test for SPFCases, but I have encountered `Runtime Exception` from `jpf`. The test is [here](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/EqSPFCasesTest1.java) and its .jpf file is [here](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/EqSPFCasesTest1.jpf). One thing to note is that the same test when I run it separately, not inside the equivalence check, runs just fine. Not sure what is going on.
Below is the runtime exception generated.

java.lang.RuntimeException: NEWARRAY: symbolic array length
	at gov.nasa.jpf.symbc.bytecode.NEWARRAY.execute(NEWARRAY.java:100)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1908)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)

**Comment by vaibhavbsharma** [comment]
Fixed. This particular crash happened because of us using a symbolic length to create the Outputs.intOutputs array. But fixing that issue caused another issue wherein we weren't finding stack slot for an output variable used in EqSPFCasesTest1.java's region. I've fixed that issue as well.
