### ISSUE TITLE
Replace_5 is failing for getSuperClassList

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#27]
Running [replace_5](https://github.com/sohah/VeritestingTransformations/blob/master/src/examples/replace.jpf) fails with exception during trying to getSuperClassList.  Failure is below:

gov.nasa.jpf.vm.ClassInfoException: class not found: cone:<Primordial,Ljava.lang.Object>
   16 = getstatic < Application, Ljava/lang/System, out, <Application,Ljava/io/PrintStream> >
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:363)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.loadClass(SystemClassLoaderInfo.java:182)
	at gov.nasa.jpf.vm.ClassInfo.resolveReferencedClass(ClassInfo.java:2411)
	at gov.nasa.jpf.vm.ThreadInfo.resolveReferencedClass(ThreadInfo.java:1244)
	at gov.nasa.jpf.symbc.veritesting.VeritestingUtil.ClassUtils.getSuperClassList(ClassUtils.java:175)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.findMethodRegion(SubstitutionVisitor.java:283)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:182)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:39)
   invokevirtual < Application, Ljava/io/PrintStream, println(Ljava/lang/String;)V > 16,17 @45 exception:18
   19 = new <Primordial,[C>@499 
	at gov.nasa.jpf.symbc.veritesting.ast.def.InvokeInstruction.accept(InvokeInstruction.java:44)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:26)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:9)
	at gov.nasa.jpf.symbc.veritesting.ast.def.CompositionStmt.accept(CompositionStmt.java:19)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:26)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:9)
	at gov.nasa.jpf.symbc.veritesting.ast.def.CompositionStmt.accept(CompositionStmt.java:19)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:127)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:39)
	at gov.nasa.jpf.symbc.veritesting.ast.def.IfThenElseStmt.accept(IfThenElseStmt.java:25)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.execute(SubstitutionVisitor.java:355)
	at gov.nasa.jpf.symbc.VeritestingListener.runVeritesting(VeritestingListener.java:305)
	at gov.nasa.jpf.symbc.VeritestingListener.runVeritestingWithSPF(VeritestingListener.java:251)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:222)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
   return 19
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFListenerException: exception during executeInstruction() notification
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:800)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
Caused by: gov.nasa.jpf.vm.ClassInfoException: class not found: cone:<Primordial,Ljava.lang.Object>
	at gov.nasa.jpf.vm.ClassLoaderInfo.getResolvedClassInfo(ClassLoaderInfo.java:363)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.getResolvedClassInfo(SystemClassLoaderInfo.java:147)
	at gov.nasa.jpf.vm.SystemClassLoaderInfo.loadClass(SystemClassLoaderInfo.java:182)
	at gov.nasa.jpf.vm.ClassInfo.resolveReferencedClass(ClassInfo.java:2411)
	at gov.nasa.jpf.vm.ThreadInfo.resolveReferencedClass(ThreadInfo.java:1244)
	at gov.nasa.jpf.symbc.veritesting.VeritestingUtil.ClassUtils.getSuperClassList(ClassUtils.java:175)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.findMethodRegion(SubstitutionVisitor.java:283)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:182)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:39)
	at gov.nasa.jpf.symbc.veritesting.ast.def.InvokeInstruction.accept(InvokeInstruction.java:44)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:26)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:9)
	at gov.nasa.jpf.symbc.veritesting.ast.def.CompositionStmt.accept(CompositionStmt.java:19)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:26)
	at gov.nasa.jpf.symbc.veritesting.ast.visitors.AstMapVisitor.visit(AstMapVisitor.java:9)
	at gov.nasa.jpf.symbc.veritesting.ast.def.CompositionStmt.accept(CompositionStmt.java:19)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:127)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.visit(SubstitutionVisitor.java:39)
	at gov.nasa.jpf.symbc.veritesting.ast.def.IfThenElseStmt.accept(IfThenElseStmt.java:25)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.substitution.SubstitutionVisitor.execute(SubstitutionVisitor.java:355)
	at gov.nasa.jpf.symbc.VeritestingListener.runVeritesting(VeritestingListener.java:305)
	at gov.nasa.jpf.symbc.VeritestingListener.runVeritestingWithSPF(VeritestingListener.java:251)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:222)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	... 14 more
} else {
   skip; 
}

**Comment by vaibhavbsharma** [comment]
This issue happens because we try to resolve SPF's ClassInfo for java.lang.Object because we think some Wala variables are of type java.lang.Object while we are trying to lookup the summary of PrintStream.println. It is weird that we thought the type of the PrintStream variable was java.lang.Object. This happened during static type inference (in StaticTypeIVisitor). @sohah Can you please look into fixing the static type inference so that we're not populating the type of Wala variables as java.lang.Object when a more specific type is available ? Another option is to not populate non-primitive types inferred from static type inference and infer non-primitive types only at instantiation time.

**Comment by sohah** [comment]
Static type inferences uses wala's type inference, we do not do anything special for that, but I can look into how to may be obtain a more precise type. However I still think that this exception shouldn't happen, we need to fail gracefully if we ended up concluding statically that a type of some var is Object, we shouldn't be crashing.

**Comment by vaibhavbsharma** [comment]
Yep, I agree. I've just committed a fix to this issue so that we don't crash if we fail to construct SPF's ClassInfo for a class. Please feel free to close this issue. Alternatively, please feel free to keep this issue open if you want a place to track changes made to the type inference so that we're making more use of type inference done at instantiation time.

**Comment by vaibhavbsharma** [comment]
Closing this issue since we're already tracking our type inference woes in the Refactoring issues list (https://github.com/sohah/VeritestingTransformations/issues/23)
