### ISSUE TITLE
PrintTokens: Simplification Turned off causes a null pointer exception

### ISSUE THREAD

**Issue by sohah** [sohah/VeritestingTransformations#34]
This issue happens on our current master as well as our paper submission version. Running printTokens with .jpf file "printtokens.2sym.mode5.jpf" with simplification turned off results in a null pointer exception below. This can be tested with jitAnalysis turned off, they actually both produce the same result. 
The exception disappears if simplification is turned on. 

[SEVERE] JPF exception, terminating: exception during executeInstruction() notification
java.lang.NullPointerException
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.arrayaccess.ArrayUtil.doArrayStore(ArrayUtil.java:122)
	at gov.nasa.jpf.symbc.VeritestingListener.populateArrayOutputs(VeritestingListener.java:699)
	at gov.nasa.jpf.symbc.VeritestingListener.setupSPF(VeritestingListener.java:519)
	at gov.nasa.jpf.symbc.veritesting.ChoiceGenerator.StaticBranchChoiceGenerator.execute(StaticBranchChoiceGenerator.java:53)
	at gov.nasa.jpf.symbc.VeritestingListener.runVeritestingWithSPF(VeritestingListener.java:392)
	at gov.nasa.jpf.symbc.VeritestingListener.runVeritestingWrapper(VeritestingListener.java:294)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:247)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
java.lang.NullPointerException
	at gov.nasa.jpf.symbc.VeritestingListener.updateSkipRegions(VeritestingListener.java:368)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:276)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFListenerException: exception during executeInstruction() notification
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:800)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
Caused by: java.lang.NullPointerException
	at gov.nasa.jpf.symbc.VeritestingListener.updateSkipRegions(VeritestingListener.java:368)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:276)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	... 14 more

Process finished with exit code 0

**Comment by vaibhavbsharma** [comment]
This issue is now fixed. The problem was simply that array stores were still using DynRegion.constantsTable if simplification is turned off using the "simplify" JPF configuration option. But if simplification is turned off, then DynRegion.constantsTable will be null.
