### ISSUE TITLE
Complex If condition assertion failure

### ISSUE THREAD

**Issue by vaibhavbsharma** [sohah/VeritestingTransformations#6]
If we run Java Ranger with the below test case, our static analysis crashes.

```Java
public int arrayTest(int index, int length) { 
        int[] x = {300, 400};
        int temp = 1;
        assert (length > 0 && index == 0 ? true : x[0] == 1 && x[1] == 400);
        return temp;
    }
```

The CFG for this method is here: 
[ir.pdf](https://github.com/sohah/VeritestingTransformations/files/2354697/ir.pdf)

The crash occurs due to the following assertion failing in CreateStaticRegions.createComplexIfCondition.
```Java
    private Expression createComplexIfCondition(ISSABasicBlock child,
                                                ISSABasicBlock entry) throws StaticRegionException {
        assert(child.getNumber() > entry.getNumber());
...
````

This assertion failure happens when we try to summarize a region that starts with BB11 and has BB15 as the terminus. The exact failure happens when ``child`` is BB9 and ``entry`` is BB11 from the above attached CFG. We end up with ``child`` being BB9 because BB9 is a parent of BB12. 

One potential fix is, inside CreateStaticRegions.createComplexIfCondition, we should never try to summarize an if condition that is outside the region. I'm not sure how this invariant is supposed to always be satisfied with the current implementation. 

Here's the complete stack trace: 
java.lang.AssertionError
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createComplexIfCondition(CreateStaticRegions.java:343)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createComplexIfCondition(CreateStaticRegions.java:368)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.findConditionalSuccessors(CreateStaticRegions.java:430)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.conditionalBranch(CreateStaticRegions.java:451)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.attemptConditionalSubregion(CreateStaticRegions.java:533)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:576)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:594)
	at gov.nasa.jpf.symbc.veritesting.ast.transformations.ssaToAst.CreateStaticRegions.createStructuredConditionalRegions(CreateStaticRegions.java:602)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.startAnalysis(VeritestingMain.java:273)
	at gov.nasa.jpf.symbc.veritesting.VeritestingMain.analyzeForVeritesting(VeritestingMain.java:99)
	at gov.nasa.jpf.symbc.VeritestingListener.discoverRegions(VeritestingListener.java:290)
	at gov.nasa.jpf.symbc.VeritestingListener.executeInstruction(VeritestingListener.java:109)
	at gov.nasa.jpf.vm.VM.notifyExecuteInstruction(VM.java:793)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1904)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)

**Comment by mwwhalen** [comment]
Fixed in commit: c5236caeb0c5b1b40c7d005730d6c1902bd49c59
